import { json } from '../lib/http.js';
import { runWithRequestContext } from '../lib/request-context.js';

export default {
  async fetch(request) {
    return runWithRequestContext(request, async () => {
      const origin = new URL(request.url).origin;
      const visibility = {name:'visibility',in:'query',required:true,schema:{type:'string',enum:['public','private']}};
      const ref = {name:'ref',in:'query',required:false,schema:{type:'string'}};
      const name = {name:'name',in:'query',required:true,schema:{type:'string'}};
      const target = {type:'string',enum:['skill','registry','factory']};
      const body = (properties, required=[]) => ({required:true,content:{'application/json':{schema:{type:'object',properties,required}}}});
      const search = [{name:'query',in:'query',required:true,schema:{type:'string'}},visibility,{name:'limit',in:'query',required:false,schema:{type:'integer',minimum:1,maximum:20,default:5}},ref];
      const migrationEndpoint={type:'object',additionalProperties:false,required:['name','visibility','ref'],properties:{name:{type:'string'},visibility:{type:'string',enum:['public','private']},ref:{type:'string'}}};
      const migrationProps={targetType:{type:'string',enum:['skill','flow']},from:migrationEndpoint,to:migrationEndpoint,dependentVisibility:{type:'string',enum:['public','private']},dependentRef:{type:'string'}};
      const paths={
        '/api/health':{get:{operationId:'healthCheck',summary:'Check whether the Factory API is running.',responses:{'200':{description:'OK'}}}},
        '/api/healthz':{get:{operationId:'healthz',summary:'Liveness check.',security:[],responses:{'200':{description:'Healthy'}}}},
        '/api/version':{get:{operationId:'getApiVersion',summary:'Return Factory API version.',security:[],responses:{'200':{description:'Version'}}}},
        '/api/readyz':{get:{operationId:'readyz',summary:'Authenticated readiness check for GitHub and configured repositories.',responses:{'200':{description:'Ready'},'503':{description:'Not ready'}}}},
        '/api/diagnostics':{get:{operationId:'getDiagnostics',summary:'Read-only diagnostics for Factory/public/private repositories, GitHub auth, base ref, rate limit, and reported permissions.',responses:{'200':{description:'Diagnostics'}}}},
        '/api/diagnostics/write-test':{post:{operationId:'runDiagnosticsWriteTest',summary:'Explicit temporary branch/file write-read-delete cleanup test.',requestBody:body({confirm:{type:'boolean'}},['confirm']),responses:{'200':{description:'Write test result and cleanup'}}}},
        '/api/preflight':{post:{operationId:'preflightWriteFiles',summary:'Validate an entire write-files batch without mutation.',requestBody:body({target,visibility:{type:'string',enum:['public','private']},branch:{type:'string'},files:{type:'array',minItems:1,items:{$ref:'#/components/schemas/WriteFile'}}},['branch','files']),responses:{'200':{description:'Preflight result'},'400':{description:'Validation failed'}}}},
        '/api/factory-module':{get:{operationId:'getFactoryModule',summary:'Load the current SKILL.md for a Factory module.',parameters:[{name:'name',in:'query',required:true,schema:{type:'string',enum:['orchestrator','architect','author','reviewer','publisher']}},ref],responses:{'200':{description:'Factory module'}}}},
        '/api/factory-file':{get:{operationId:'getFactoryFile',summary:'Read one UTF-8 source file from the Agent Skill Factory repository.',parameters:[{name:'path',in:'query',required:true,schema:{type:'string'}},ref],responses:{'200':{description:'Factory source file'}}}},
        '/api/skills':{get:{operationId:'listSkills',summary:'List Skills.',parameters:[visibility,ref],responses:{'200':{description:'Skill list'}}}},
        '/api/search-skills':{get:{operationId:'searchSkills',summary:'Search Skills by name and SKILL.md metadata.',parameters:search,responses:{'200':{description:'Matching Skills'}}}},
        '/api/skill':{get:{operationId:'getSkill',summary:"Load a Skill's SKILL.md.",parameters:[visibility,name,ref],responses:{'200':{description:'Skill'}}}},
        '/api/skill-file':{get:{operationId:'getSkillFile',summary:'Load one text resource within a Skill.',parameters:[visibility,name,{name:'path',in:'query',required:true,schema:{type:'string'}},ref],responses:{'200':{description:'Skill file'}}}},
        '/api/flows':{get:{operationId:'listFlows',summary:'List saved Flows.',parameters:[visibility,ref],responses:{'200':{description:'Flow list'}}}},
        '/api/search-flows':{get:{operationId:'searchFlows',summary:'Search saved Flows independently from Skill discovery.',parameters:search,responses:{'200':{description:'Matching Flows'}}}},
        '/api/flow':{get:{operationId:'getFlow',summary:"Load a Flow's FLOW.json.",parameters:[visibility,name,ref],responses:{'200':{description:'Flow'}}}},
        '/api/suites':{get:{operationId:'listSuites',summary:'List Suites.',parameters:[visibility,ref],responses:{'200':{description:'Suite list'}}}},
        '/api/search-suites':{get:{operationId:'searchSuites',summary:'Search Suites.',parameters:search,responses:{'200':{description:'Matching Suites'}}}},
        '/api/suite':{get:{operationId:'getSuite',summary:"Load a Suite's SUITE.json.",parameters:[visibility,name,ref],responses:{'200':{description:'Suite'}}}},
        '/api/registry-dependents':{get:{operationId:'getRegistryDependents',summary:'Find reverse Registry dependencies within one explicitly selected Registry scope/ref.',parameters:[{name:'targetType',in:'query',required:true,schema:{type:'string',enum:['skill','flow']}},{name:'targetName',in:'query',required:true,schema:{type:'string'}},{name:'targetVisibility',in:'query',required:true,schema:{type:'string',enum:['public','private']}},{name:'dependentVisibility',in:'query',required:true,schema:{type:'string',enum:['public','private']}},{name:'ref',in:'query',required:true,schema:{type:'string'}}],responses:{'200':{description:'Dependents'}}}},
        '/api/plan-registry-reference-migration':{post:{operationId:'planRegistryReferenceMigration',summary:'Plan a read-only structural Registry reference migration.',requestBody:body(migrationProps,['targetType','from','to','dependentVisibility','dependentRef']),responses:{'200':{description:'Migration plan'}}}},
        '/api/apply-registry-reference-migration':{post:{operationId:'applyRegistryReferenceMigration',summary:'Apply a planned structural Registry reference migration with SHA protection.',requestBody:body({...migrationProps,expectedFiles:{type:'array',items:{type:'object',required:['path','sha'],properties:{path:{type:'string'},sha:{type:'string'}}}},message:{type:'string'}},['targetType','from','to','dependentVisibility','dependentRef','expectedFiles']),responses:{'200':{description:'Migration result'}}}},
        '/api/skill-history':{get:{operationId:'getSkillHistory',summary:'Get recent history for a Skill or Factory module.',parameters:[{name:'target',in:'query',required:false,schema:{type:'string',enum:['skill','flow','suite','factory'],default:'skill'}},{name:'visibility',in:'query',required:false,schema:{type:'string',enum:['public','private']}},name,ref],responses:{'200':{description:'History'}}}},
        '/api/registry-history':{get:{operationId:'getRegistryHistory',summary:'Get recent history for a Skill, Flow, Suite, or Factory module.',parameters:[{name:'target',in:'query',required:true,schema:{type:'string',enum:['skill','flow','suite','factory']}},{name:'visibility',in:'query',required:false,schema:{type:'string',enum:['public','private']}},name,ref],responses:{'200':{description:'History'}}}},
        '/api/create-branch':{post:{operationId:'createChangeBranch',summary:'Create or safely reuse a change branch.',requestBody:body({target,visibility:{type:'string',enum:['public','private']},branch:{type:'string'},base:{type:'string'}},['branch']),responses:{'200':{description:'Created or already exists'}}}},
        '/api/write-files':{post:{operationId:'writeRegistryFiles',summary:'Preflight then create or replace UTF-8 text files on a change branch.',requestBody:body({target,visibility:{type:'string',enum:['public','private']},branch:{type:'string'},message:{type:'string'},files:{type:'array',minItems:1,items:{$ref:'#/components/schemas/WriteFile'}}},['branch','files']),responses:{'200':{description:'Files written'},'409':{description:'Conflict or stale SHA'}}}},
        '/api/delete-file':{post:{operationId:'deleteRegistryFile',summary:'Delete one text file on a change branch with dependency-aware guards.',requestBody:body({target,visibility:{type:'string',enum:['public','private']},branch:{type:'string'},path:{type:'string'},message:{type:'string'},dependencyRefs:{type:'object',properties:{privateRef:{type:'string'}}}},['branch','path']),responses:{'200':{description:'File deleted'},'409':{description:'Dependency conflict'}}}},
        '/api/validate-skill':{post:{operationId:'validateSkill',summary:'Validate proposed SKILL.md text and scan obvious secrets.',requestBody:body({skillMd:{type:'string'}},['skillMd']),responses:{'200':{description:'Validation result'}}}},
        '/api/validate-flow':{post:{operationId:'validateFlow',summary:'Validate a proposed or stored FLOW.json.',requestBody:body({visibility:{type:'string',enum:['public','private']},name:{type:'string'},ref:{type:'string'},flowJson:{type:'string'}},['visibility','name']),responses:{'200':{description:'Validation result'}}}},
        '/api/validate-suite':{post:{operationId:'validateSuite',summary:'Validate a proposed or stored SUITE.json.',requestBody:body({visibility:{type:'string',enum:['public','private']},name:{type:'string'},ref:{type:'string'},suiteJson:{type:'string'}},['visibility','name']),responses:{'200':{description:'Validation result'}}}},
        '/api/compare':{get:{operationId:'compareChangeBranch',summary:'Compare a change branch and report stale/ahead/behind. Patches are excluded by default.',parameters:[{name:'target',in:'query',required:false,schema:target},{name:'visibility',in:'query',required:false,schema:{type:'string',enum:['public','private']}},{name:'head',in:'query',required:true,schema:{type:'string'}},{name:'base',in:'query',required:false,schema:{type:'string',default:'main'}},{name:'includePatch',in:'query',required:false,schema:{type:'boolean',default:false}}],responses:{'200':{description:'Compact diff by default; patch included only when requested'}}}},
        '/api/pull-request':{post:{operationId:'openSkillPullRequest',summary:'Open a PR after stale-branch guard.',requestBody:body({target,visibility:{type:'string',enum:['public','private']},head:{type:'string'},base:{type:'string'},title:{type:'string'},body:{type:'string'},allowStale:{type:'boolean',default:false}},['head','title']),responses:{'200':{description:'PR opened'},'409':{description:'Stale branch refused'}}}}
      };
      return json({openapi:'3.1.0',info:{title:'Agent Skill Factory Registry API',version:'0.9.0'},servers:[{url:origin}],paths,components:{schemas:{WriteFile:{type:'object',required:['path','content'],properties:{path:{type:'string'},content:{type:'string'},expectedSha:{type:['string','null'],description:'String enables compare-and-swap; null permits create-only; omitted preserves legacy update behavior.'}}}},securitySchemes:{bearerAuth:{type:'http',scheme:'bearer'}}},security:[{bearerAuth:[]}]});
    });
  }
};
